export enum FIELDS {
  FIRST_NAME = "firstName",
  LAST_NAME = "lastName",
  EMAIL = "email",
  COUNTRY_CODE = "countryCode",
  CONTACT_NUMBER = "phone",
  PERSON = "person",
  SPECIAL_REQUIREMENTS = "specialRequirements",
  PICKUP_LOCATION = "pickupLocation",
  PERSON_ID = "personId",
}

export type PersonDetails = {
  [FIELDS.FIRST_NAME]: string;
  [FIELDS.LAST_NAME]: string;
  [FIELDS.PERSON_ID]: number;
} & { [key: string]: string | number };

export interface ContactDetailsFormData {
  [FIELDS.FIRST_NAME]: string;
  [FIELDS.LAST_NAME]: string;
  [FIELDS.EMAIL]: string;
  [FIELDS.COUNTRY_CODE]: string;
  [FIELDS.CONTACT_NUMBER]: string;
}

export type BookingDetailsFormData = {
  [FIELDS.PERSON]: PersonDetails[];
  [FIELDS.SPECIAL_REQUIREMENTS]: string;
  [FIELDS.PICKUP_LOCATION]?: string;
} & { [key: string]: any };

export enum PROMO_CODE_STATUS_ERROR {
  INVALID_PROMOCODE = "INVALID_PROMOCODE",
  EXPIRED_PROMOCODE = "EXPIRED_PROMOCODE",
  DISABLED_PROMOCODE = "DISABLED_PROMOCODE",
  USED_COMPLETELY = "USED_COMPLETELY",
  GEO_WRONG = "GEO_WRONG",
  CATEGORY_WRONG = "CATEGORY_WRONG",
  DISCOUNT_NOT_ALLOWED = "DISCOUNT_NOT_ALLOWED",
  CURRENCY_WRONG = "CURRENCY_WRONG",
  MINIMUM_ORDER_NOT_MET = "MINIMUM_ORDER_NOT_MET",
  PRODUCT_NOT_INCLUDED = "PRODUCT_NOT_INCLUDED",
  PRODUCT_EXCLUDED = "PRODUCT_EXCLUDED",
}

export type PROMO_CODE_STATUS_ERROR_MESSAGE = {
  [PROMO_CODE_STATUS_ERROR.INVALID_PROMOCODE]: string;
  [PROMO_CODE_STATUS_ERROR.EXPIRED_PROMOCODE]: string;
  [PROMO_CODE_STATUS_ERROR.DISABLED_PROMOCODE]: string;
  [PROMO_CODE_STATUS_ERROR.USED_COMPLETELY]: string;
  [PROMO_CODE_STATUS_ERROR.GEO_WRONG]: string;
  [PROMO_CODE_STATUS_ERROR.CATEGORY_WRONG]: string;
  [PROMO_CODE_STATUS_ERROR.DISCOUNT_NOT_ALLOWED]: string;
  [PROMO_CODE_STATUS_ERROR.CURRENCY_WRONG]: string;
  [PROMO_CODE_STATUS_ERROR.MINIMUM_ORDER_NOT_MET]: string;
  [PROMO_CODE_STATUS_ERROR.PRODUCT_NOT_INCLUDED]: string;
  [PROMO_CODE_STATUS_ERROR.PRODUCT_EXCLUDED]: string;
};
